const routes = {
    home: '/',
    week2: '/week2',
    t2ex1: '/week2/exercise1',
    t2ex2: '/week2/exercise2',
    t2ex3: '/week2/exercise3',
    t2ex4: '/week2/exercise4',
    t2ex5: '/week2/exercise5',
    t2ex6: '/week2/exercise6',
    t2ex7: '/week2/exercise7',
    week3: '/week3',
    t3ex1: '/week3/exercise1',
    t3ex2: '/week3/exercise2',
    week4: '/week4',
    t4ex1: '/week4/exercise1',
    week5: '/week5',
    t5ex1: '/week5/exercise1',
    t5ex2: '/week5/exercise2',
    t5ex3: '/week5/exercise3',
    week6: '/week6',
    t6ex1: '/week6/exercise1',
    week7: '/week7',
    dashboard: '/week7/dashboard',
    project: '/week7/project',
    teams: '/week7/teams',
    analytics: '/week7/analytics',
    messages: '/week7/message',
    integrations: '/week7/integrations',
};

export default routes;
